wikidata_server = "http://sitaware.isi.edu:8080/bigdata/namespace/wdq/sparql"
# wikidata_server_test = "http://sitaware.isi.edu:8080/bigdata/namespace/datamart3/sparql"
general_search_server = "http://dsbox02.isi.edu:9001/blazegraph/namespace/datamart3/sparql"
memcache_server = "dsbox02.isi.edu:11211"
wikifier_server = "http://dsbox02.isi.edu/wikifier/get_identifiers"
